### ISSUE TITLE
React / 05_Working_Together_Composing_Components does not work

### ISSUE THREAD

**Issue by vitalyzhakov** [kotlin-hands-on/hands-on#131]
Hello!

Thanks for your work!

I have executed manual https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/05_Working_Together_Composing_Components, but it does not works without code in corresponding repo
https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle/blob/step-04-composing-components/src/main/kotlin/VideoList.kt#L33-L37
```kotlin
fun RBuilder.videoList(handler: VideoListProps.() -> Unit): ReactElement {
    return child(VideoList::class) {
        this.attrs(handler)
    }
}
```
I think, this manual page is uncompleted now.

**Comment by SebastianAigner** [comment]
Hey! We’ve overhauled the code for this tutorial. I hope that fixes your problem. If any problems remain, please do not hesitate to file another issue.
