### ISSUE TITLE
Code from tutorial not working

### ISSUE THREAD

**Issue by NerdPractitioner** [kotlin-hands-on/hands-on#41]
Hi, Sorry if this isn't a place for support of the actual tutorial content but I'm immediately running into issues. after I've installed npm and yarn but yarn start doesn't work. I've included code after yarn create react-kotlin-app confexplorer

`Success! Created confexplorer at D:\github\kotlin-projects\test1\confexplorer
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd confexplorer
  yarn start

Happy hacking!
Done in 276.84s.
PS D:\github\kotlin-projects\test1> cd confexplorer
PS D:\github\kotlin-projects\test1\confexplorer> yarn start
yarn run v1.17.3
$ react-scripts-kotlin start
[34mi[39m [90m｢wds｣[39m: Project is running at http://192.168.1.227/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\github\kotlin-projects\test1\confexplorer\public
i ｢wds｣: 404s will fallback to /index.html
Starting the development server...

D:\GitHub\kotlin-projects\test1\confexplorer\node_modules\react-scripts-kotlin\scripts\start.js:19
  throw err;
  ^

Error: ENOENT: no such file or directory, mkdir 'D:\github\kotlin-projects\test1\confexplorer\node_modules\.cache\kotlin-webpack'
    at Object.mkdirSync (fs.js:834:3)
    at KotlinWebpackPlugin.generateErrorBundle (D:\GitHub\kotlin-projects\test1\confexplorer\node_modules\@jetbrains\kotlin-webpack-plugin\plugin.js:249:10)
    at KotlinWebpackPlugin.compileIfFirstRun (D:\GitHub\kotlin-projects\test1\confexplorer\node_modules\@jetbrains\kotlin-webpack-plugin\plugin.js:199:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'D:\\github\\kotlin-projects\\test1\\confexplorer\\node_modules\\.cache\\kotlin-webpack'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by SebastianAigner** [comment]
Thank you for reporting the issue! This seems like a problem related to running Create-React-Kotlin-App on Windows. I've created an issue for the team here: https://youtrack.jetbrains.com/issue/CRKA-123
I'll make sure to update you once we've hunted down the issue behind it and can supply a fix.

**Comment by SebastianAigner** [comment]
Late update; we've since updated the Kotlin/JS tutorial with a version that uses Gradle, so I am closing this issue for now. Sharing the build system that you're already familiar with from other Kotlin projects hopefully makes it a little bit easier to get started.

If you feel like it, give it a whirl at https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/01_Introduction !

However, if you run into any more issues with the new tutorial, please feel free to log them.
