### ISSUE TITLE
Dead link in Targeting iOS and Android with Kotlin Multiplatform/06_SettingUpKotlinFramework.md

### ISSUE THREAD

**Issue by mariolourobert** [kotlin-hands-on/hands-on#54]
In the page : https://github.com/kotlin-hands-on/hands-on/blob/master/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/06_SettingUpKotlinFramework.md

The following link is dead :
[Kotlin/Native as an Apple Framework](/docs/tutorials/native/apple-framework.html)

**Comment by rendner** [comment]
There is already a PR for this dead link: #51

**Comment by SebastianAigner** [comment]
Has been fixed. Thanks for reporting, and sorry for the delays!
