### ISSUE TITLE
Link to github refers to old repository

### ISSUE THREAD

**Issue by marty30** [kotlin-hands-on/hands-on#62]
Het first page gives a link to this GitHub repo: https://github.com/kotlin-hands-on/web-app-react-kotlin-js, yet this repo sends me to https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle.

**Comment by marty30** [comment]
Probably refers to commit 6f3afd1

**Comment by SebastianAigner** [comment]
Thanks for the report and sorry for the delay! I've just merged #67 , which fixes this issue.
