### ISSUE TITLE
build.gradle.kts config complains about plugins since settings.gradle.kts is not updated

### ISSUE THREAD

**Issue by marty30** [kotlin-hands-on/hands-on#63]
After applying the changes to my build.gradle.kts file, gradle cannot find the kotlin-js plugin. After looking this up in the GitHub repo, I found that settings.gradle.kts is not similar. After adding a pluginManagement section, my project compiles.

Note that this is really unclear for somebody without Gradle experience.

**Comment by marty30** [comment]
Probably refers to commit 6f3afd1

**Comment by SebastianAigner** [comment]
Sorry for the oversight! After releasing Kotlin version 1.3.70, we've updated the hands-on to use non-EAP artifacts, so an extra adjustment of `settings.gradle.kts` is no longer necessary. Good to hear you managed to work around this problem with the help of the example project!
