### ISSUE TITLE
Unresolved reference registerChatRoutes

### ISSUE THREAD

**Issue by tgsd96** [kotlin-hands-on/hands-on#73]
I am trying the hands on, Creating a Chat App with WebSockets and on step 4 i.e. setting up a web server the function registerChatRoute comes out of no where. So the compiler is showing error as unsolved reference. I tried the documentation but couldn't find detail on how to include a Route.route to Application.module

![Screenshot 2020-04-15 at 1 34 00 PM](https://user-images.githubusercontent.com/11096755/79313389-e15d7900-7f1d-11ea-8e1d-fa810084ffab.png)

**Comment by hhariri** [comment]
Sorry about that. I've updated hands-on to include this info. You need to basically add the following code to Chat.kt

```kotlin
fun Application.registerChatRoutes() {
    routing {
        chatRoute()
    }
}
```
