### ISSUE TITLE
Code indent not working for hocon

### ISSUE THREAD

**Issue by dodalovic** [kotlin-hands-on/hands-on#76]
https://play.kotlinlang.org/hands-on/Creating%20a%20Chat%20App%20with%20WebSockets/05_setting-up-server

![image](https://user-images.githubusercontent.com/6358061/80025247-9bd21a80-84e0-11ea-9c7d-b2f7cf1827be.png)

**Comment by AlexanderPrendota** [comment]
Thanks. Fixed.
cc @hhariri
